from pydantic import BaseModel, Field
from typing import Optional, Dict, List

class ComplianceAnalysisRequest(BaseModel):
    project_url: str = Field(..., description="GitLab Project URL or Project ID")
    branch: Optional[str] = Field(None, description="Optional branch name to analyze (falls back to default branch if omitted)")
    pat: Optional[str] = Field(None, description="Optional GitLab Personal Access Token for private repos or rate limit avoidance")

class BatchAnalysisRequest(BaseModel):
    project_urls: List[str] = Field(..., description="List of GitLab Project URLs or Project IDs to analyze")
    branch: Optional[str] = Field(None, description="Optional branch name to analyze for all repositories")
    pat: Optional[str] = Field(None, description="Optional GitLab Personal Access Token")

class ComplianceReportResponse(BaseModel):
    id: str = Field(..., description="Unique compliance report ID")
    project_id: str = Field(..., description="GitLab Project ID")
    project_name: str = Field(..., description="GitLab Project Name")
    project_url: str = Field(..., description="GitLab Project URL")
    branch: str = Field(..., description="Analyzed branch name")
    score: float = Field(..., description="Overall compliance score (percentage)")
    risk_level: str = Field(..., description="Risk Level (Critical, High, Medium, Low)")
    metadata_score: float = Field(..., description="Project Metadata category score")
    documentation_score: float = Field(..., description="Documentation Validation category score")
    health_score: float = Field(..., description="Repository Health category score")
    code_quality_score: float = Field(..., description="Code Quality category score")
    security_score: float = Field(..., description="Security Validation category score")
    testing_score: float = Field(..., description="Testing Validation category score")
    cicd_score: float = Field(..., description="CI/CD Validation category score")
    spec_kit_score: float = Field(..., description="Spec-Kit Validation category score")
    checks_passed: int = Field(..., description="Number of passed compliance checks")
    checks_failed: int = Field(..., description="Number of failed compliance checks")
    checks_total: int = Field(..., description="Total number of compliance checks")
    details: Dict[str, bool] = Field(..., description="Dictionary containing results of each individual check (True = Pass, False = Fail)")
    missing_files: List[str] = Field(..., description="List of missing configuration/documentation files")
    suggestions: str = Field(..., description="Remediation instructions and code templates generated by AI")
    analysis_logs: List[Dict[str, str]] = Field(..., description="Real-time scanning activity logs")
    created_at: str = Field(..., description="ISO timestamp when the analysis was performed")

class TrendPoint(BaseModel):
    date: str = Field(..., description="ISO timestamp or date string")
    score: float = Field(..., description="Compliance score at this point in time")

class ProjectHistoryResponse(BaseModel):
    project_url: str = Field(..., description="GitLab Project URL")
    project_name: str = Field(..., description="GitLab Project Name")
    history: List[ComplianceReportResponse] = Field(..., description="Chronological scan reports")
    trends: List[TrendPoint] = Field(..., description="Historical trend data points")

class ComparisonItem(BaseModel):
    project_name: str = Field(..., description="Project Name")
    project_url: str = Field(..., description="Project URL")
    score: float = Field(..., description="Overall score")
    risk_level: str = Field(..., description="Risk level")
    checks_passed: int = Field(..., description="Passed checks count")
    checks_failed: int = Field(..., description="Failed checks count")
    created_at: str = Field(..., description="Scan date")

class TeamComparisonResponse(BaseModel):
    projects: List[ComparisonItem] = Field(..., description="List of compared projects")
    average_score: float = Field(..., description="Average compliance score across compared projects")
